//
// Created by ted on 2022-03-17.
//

#ifndef WW_C_STEPANALYZER_MAIN_H
#define WW_C_STEPANALYZER_MAIN_H
#define LAG 5
#define THRESHOLD 3
#define INFLUENCE 0.5
#define MIN_DEGREES_SEC_FOR_PEAK 20.0
#define MIN_NUM_PEAKS_FOR_HEEL_STRIKE  3
#define SKIP_FLAT_FOOT_SAMPLES  15
#define SKIP_HEEL_OFF_SAMPLES  5
#endif //WW_C_STEPANALYZER_MAIN_H
#define SAMPLE_LENGTH 1000
